apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-bitnami
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    chart: nginx
    targetRevision: 20.0.7
    helm:
      valueFiles:
      - $values
      values: |
        image:
          tag: 1.110.0
  - repoURL: 'https://github.com/Nirm01/helm-argocd'
    targetRevision: main
    ref: values
    path: argocd
    

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-helm

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
