apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-bitnami
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.5.2
    chart: nginx
    helm:
      valueFiles:
      - values.yaml
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    chart: nginx
    targetRevision: 15.5.2
    helm:
      valueFiles:
      - $values/values.yaml
  - repoURL: 'https://github.com/Nirm01/helm-argocd'
    targetRevision: main
    ref: values
    path: argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-helm

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
